source "%val{config}/kakudite/bundle.kak"
source "%val{config}/kakudite/options.kak"
source "%val{config}/kakudite/definitions.kak"
source "%val{config}/kakudite/general-mappings.kak"
source "%val{config}/kakudite/clipboard.kak"
source "%val{config}/kakudite/recentf.kak"
source "%val{config}/kakudite/emoji.kak"
source "%val{config}/kakudite/custom-tmux.kak"
source "%val{config}/kakudite/custom-zellij.kak"
source "%val{config}/kakudite/scrolloff.kak"
source "%val{config}/kakudite/custom-filetypes/solidity.kak"
# Disable if it eats too much CPU because project has lots of files 
# source "%val{config}/kakudite/ripgrep-completer.kak"
# source "%val{config}/kakudite/fd-completer.kak"

